import type { Project } from "@/lib/types";

export const projects: Project[] = [
  {
    slug: "magda-ogrod",
    title: "Ogród Magdy",
    description: "Kompleksowy projekt i realizacja ogrodu przydomowego w harmonii z naturą.",
    coverImage: "/images/portfolio/magda-ogrod/m1.jpg",
    images: [
      "/images/portfolio/magda-ogrod/m1.jpg",
      "/images/portfolio/magda-ogrod/m2.jpg",
      "/images/portfolio/magda-ogrod/m3.jpg",
      "/images/portfolio/magda-ogrod/m4.jpg",
      "/images/portfolio/magda-ogrod/m5.jpg",
      "/images/portfolio/magda-ogrod/m6.jpg",
      "/images/portfolio/magda-ogrod/m7.jpg",
      "/images/portfolio/magda-ogrod/m8.jpg",
      "/images/portfolio/magda-ogrod/m9.jpg",
      "/images/portfolio/magda-ogrod/m10.jpg",
      "/images/portfolio/magda-ogrod/m11.jpg",
      "/images/portfolio/magda-ogrod/m12.jpg",
    ],
  },
  {
    slug: "magda-ogrod-dodatki",
    title: "Ogród Magdy — Dodatki",
    description: "Uzupełnienia i detale małej architektury ogrodowej.",
    coverImage: "/images/portfolio/magda-ogrod_dodatki/md1.jpg",
    images: [
      "/images/portfolio/magda-ogrod_dodatki/md1.jpg",
      "/images/portfolio/magda-ogrod_dodatki/md2.jpg",
      "/images/portfolio/magda-ogrod_dodatki/md3.jpg",
      "/images/portfolio/magda-ogrod_dodatki/md4.jpg",
      "/images/portfolio/magda-ogrod_dodatki/md5.jpg",
      "/images/portfolio/magda-ogrod_dodatki/md6.jpg",
      "/images/portfolio/magda-ogrod_dodatki/md7.jpg",
      "/images/portfolio/magda-ogrod_dodatki/md8.jpg",
      "/images/portfolio/magda-ogrod_dodatki/md9.jpg",
      "/images/portfolio/magda-ogrod_dodatki/md10.jpg",
      "/images/portfolio/magda-ogrod_dodatki/md11.jpg",
      "/images/portfolio/magda-ogrod_dodatki/md12.jpg",
    ],
  },
  {
    slug: "zaya-karpacz",
    title: "Projekt Karpacz",
    description: "Ogród górski z tarasem widokowym — projekt w Karpaczu.",
    coverImage: "/images/portfolio/zaya_karpacz/1karpacz.jpg",
    images: [
      "/images/portfolio/zaya_karpacz/1karpacz.jpg",
      "/images/portfolio/zaya_karpacz/2karpacz.jpg",
      "/images/portfolio/zaya_karpacz/4karpacz.jpg",
      "/images/portfolio/zaya_karpacz/5karpacz.jpg",
    ],
  },
  {
    slug: "zaya-dziwiszow",
    title: "Projekt Dziwiszów",
    description: "Nowoczesny ogród przy domu jednorodzinnym w Dziwiszowie.",
    coverImage: "/images/portfolio/zaya_dziwiszow/1Dziwiszow.jpg",
    images: [
      "/images/portfolio/zaya_dziwiszow/1Dziwiszow.jpg",
      "/images/portfolio/zaya_dziwiszow/2Dziwiszow.jpg",
      "/images/portfolio/zaya_dziwiszow/3Dziwiszow.jpg",
      "/images/portfolio/zaya_dziwiszow/4Dziwiszow.jpg",
      "/images/portfolio/zaya_dziwiszow/5Dziwiszow.jpg",
      "/images/portfolio/zaya_dziwiszow/6Dziwiszow.jpg",
      "/images/portfolio/zaya_dziwiszow/7Dziwiszow.jpg",
      "/images/portfolio/zaya_dziwiszow/8Dziwiszow.jpg",
      "/images/portfolio/zaya_dziwiszow/9Dziwiszow.jpg",
      "/images/portfolio/zaya_dziwiszow/10Dziwiszow.jpg",
      "/images/portfolio/zaya_dziwiszow/11Dziwiszow.jpg",
      "/images/portfolio/zaya_dziwiszow/12Dziwiszow.jpg",
    ],
  },
  {
    slug: "krzysiu-beata-lazienka",
    title: "Łazienka Krzysia i Beaty",
    description: "Projekt i realizacja nowoczesnej łazienki — przytulna przestrzeń dla dwojga.",
    coverImage: "/images/portfolio/krzysiu-beata-lazienka/1kb.jpg",
    images: [
      "/images/portfolio/krzysiu-beata-lazienka/1kb.jpg",
      "/images/portfolio/krzysiu-beata-lazienka/2kb.jpg",
      "/images/portfolio/krzysiu-beata-lazienka/3kb.jpg",
      "/images/portfolio/krzysiu-beata-lazienka/4kb.jpg",
      "/images/portfolio/krzysiu-beata-lazienka/5kb.jpg",
      "/images/portfolio/krzysiu-beata-lazienka/6kb.jpg",
      "/images/portfolio/krzysiu-beata-lazienka/7kb.jpg",
      "/images/portfolio/krzysiu-beata-lazienka/8kb.jpg",
      "/images/portfolio/krzysiu-beata-lazienka/9kb.jpg",
      "/images/portfolio/krzysiu-beata-lazienka/10kb.jpg",
      "/images/portfolio/krzysiu-beata-lazienka/11kb.jpg",
    ],
  },
];
